### ISSUE TITLE
Backup rotate + disk extension

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.blue-green#2]
1. Cron job for backup rotation
2. Ask for a disk extension
3. Clean up (very) old docker images

**Comment by ponsfrilus** [comment]
1. Cron job for backup rotation: `/etc/cron.hourly/backup-sti-epfl-ch`
2. Ask for a disk extension
3. ~~Clean up (very) old docker images~~ done with `docker system prune`

**Comment by ponsfrilus** [comment]
Fixed by cad4367

**Comment by domq** [comment]
@ponsfrilus

**Comment by ponsfrilus** [comment]
:1st_place_medal:
